.gitignore
Tests/winswTests/winswTests.csproj
pom.xml
winsw.csproj
winsw.sln

Port WinSW to Visual Studio Community 2013

---

Advapi32.cs
Kernel32.cs
Main.cs
README.markdown
ServiceDescriptor.cs
Tests/winswTests/ServiceDescriptorTests.cs

See PR #64 for context and review.

Adding logon as a service right to user account specified in configuration

---

Main.cs
README.markdown
ServiceDescriptor.cs
Tests/winswTests/ServiceDescriptorTests.cs

Add ability to set startup type to XML file

---

ServiceDescriptor.cs

Fix needing to call install command from same directory.

---

Main.cs
Properties/AssemblyInfo.cs
Tests/winswTests/MainTest.cs
Tests/winswTests/Util/CLITestHelper.cs
Tests/winswTests/packages.config
Tests/winswTests/winswTests.csproj
packages/repositories.config

This rework minimally impacts the project structure.
Command line parsing and management will be improved in winsw-2.0
Resolves #78 and #46
Related to #80
Signed-off-by: Oleg Nenashev <o.v.nenashev@gmail.com>

Add "version" and "help", handle unsupported commands

---

Main.cs

Changes:
* install - Fail the installation if the service exists
* uninstall - Print warning if the service does not exist
Resolves #55
Signed-off-by: Oleg Nenashev <o.v.nenashev@gmail.com>

Better diagnosis in install and uninstall commands

---

src/Core/ServiceWrapper/Main.cs

[Issue #124] - Prevent the CPU overutilization due to the usage of Milliseconds instead of TotalMsec

---

CHANGELOG.md
README.md
doc/extensions/extensions.md
doc/extensions/runawayProcessKiller.md
doc/extensions/sharedDirectoryMapper.md

Just fixes the current state of extensions in the documentation
@reviewbybees

Document the extension engine and exisitng extensions

---

doc/xmlConfigFile.md

Added example of configuring WinSW to use GMSA. Tested with Windows Server 2012 R2.

How to use (Group) Managed Service Accounts

---

README.md
WinSW.nuspec
appveyor.yml

Issue #65 - Add NuGet packaging

---

CHANGELOG.md
README.md
doc/installation.md

Documentation updates towards 2.0

---

src/Core/ServiceWrapper/Main.cs
src/Core/WinSWCore/Native/Kernel32.cs

Issue #85 - Use SafeFileHandle of the deprecated FileHandle in the /redirect mode

---

WinSW.nuspec

Issue #176 - Attach allOptions sample as a reference config to the NuGet package

---

src/Core/WinSWCore/ServiceDescriptor.cs
src/Test/winswTests/ServiceDescriptorTests.cs

See #178. This PR adds a single-line fix and several unit tests of the related logic
@reviewbybees

Fix #178 - Improper handling of the arguments parameter

---

doc/puppetWinSW.md

Updated the documentation to include new functionality.

Update of Puppet Module Documentation

---

CHANGELOG.md

Noting 2.1.0

---

src/Core/WinSWCore/ServiceDescriptor.cs

Textbook example of what will eventually happen if you copy-paste enough snippets?

Noticed a small 'error' and fixed it

---

src/Core/ServiceWrapper/Main.cs

allow to create configured WrapperService instances

pass ServiceDescriptor when creating wrapperservice

---

examples/sample-allOptions.xml
examples/sample-minimal.xml
src/Test/winswTests/Configuration/ExamplesTest.cs

Fix spelling in samples

---

.github/CODEOWNERS

I do not want to miss PRs from @NextTurn :)

Add CODEOWNERS to automate code review requests

---

src/Core/ServiceWrapper/Logging/WrapperServiceEventLogProvider.cs
src/Core/ServiceWrapper/Main.cs
src/Core/ServiceWrapper/NullableAttributes.cs
src/Core/ServiceWrapper/SigIntHelper.cs
src/Core/ServiceWrapper/winsw.csproj
src/Core/WinSWCore/Configuration/DefaultSettings.cs
src/Core/WinSWCore/Configuration/IWinSWConfiguration.cs
src/Core/WinSWCore/Download.cs
src/Core/WinSWCore/DynamicProxy.cs
src/Core/WinSWCore/Extensions/AbstractWinSWExtension.cs
src/Core/WinSWCore/Extensions/IWinSWExtension.cs
src/Core/WinSWCore/Extensions/WinSWExtensionDescriptor.cs
src/Core/WinSWCore/Extensions/WinSWExtensionManager.cs
src/Core/WinSWCore/LogAppenders.cs
src/Core/WinSWCore/Logging/IServiceEventLogProvider.cs
src/Core/WinSWCore/Logging/ServiceEventLogAppender.cs
src/Core/WinSWCore/Native/Advapi32.cs
src/Core/WinSWCore/Native/Kernel32.cs
src/Core/WinSWCore/NullableAttributes.cs
src/Core/WinSWCore/ServiceDescriptor.cs
src/Core/WinSWCore/Util/ProcessHelper.cs
src/Core/WinSWCore/Util/SigIntHelper.cs
src/Core/WinSWCore/Util/XmlHelper.cs
src/Core/WinSWCore/WinSWCore.csproj
src/Core/WinSWCore/Wmi.cs
src/Core/WinSWCore/WmiSchema.cs
src/Plugins/RunawayProcessKiller/RunawayProcessKiller.csproj
src/Plugins/RunawayProcessKiller/RunawayProcessKillerExtension.cs
src/Plugins/SharedDirectoryMapper/SharedDirectoryMapper.cs
src/Plugins/SharedDirectoryMapper/SharedDirectoryMapper.csproj

Closes #88 
Based on #354 
It's unclear to me how to annotate those properties. See suppressed warnings in https://github.com/kohsuke/winsw/commit/31d1d134264e6e2bedfc1659dd8773cfdc82d726, https://github.com/kohsuke/winsw/commit/6d57da2c92fce41cc917c8881dd8391a1b3d8c00.

Annotate for nullable reference types

---

src/Core/ServiceWrapper/Main.cs
src/Core/WinSWCore/LogAppenders.cs
src/Core/WinSWCore/Native/Advapi32.cs
src/Core/WinSWCore/PeriodicRollingCalendar.cs
src/Plugins/SharedDirectoryMapper/SharedDirectoryMapper.cs
src/Plugins/SharedDirectoryMapper/SharedDirectoryMapperConfig.cs
src/Plugins/SharedDirectoryMapper/SharedDirectoryMapperHelper.cs
src/Test/winswTests/DownloadTest.cs
src/Test/winswTests/Extensions/RunawayProcessKillerTest.cs
src/Test/winswTests/Extensions/SharedDirectoryMapperTest.cs
src/Test/winswTests/ServiceDescriptorTests.cs
src/Test/winswTests/Util/CLITestHelper.cs
src/Test/winswTests/Util/ConfigXmlBuilder.cs
src/Test/winswTests/Util/ExceptionHelper.cs
src/Test/winswTests/Util/ProcessHelperTest.cs
src/Test/winswTests/winswTests.csproj

Simplify syntax

---

examples/sample-allOptions.xml
examples/sample-minimal.xml

Fix configuration samples

---

appveyor.yml

Disable Nuget account and project feeds to fix CI

---

appveyor-release.yml

See https://github.com/kohsuke/winsw/issues/378

Fix the release flow after packaging changes

---

appveyor.yml

CC @NextTurn . It fixes extensions of files which is important for further deployment to GitHub Releases.

Fix file extensions for .NET Core artifacts

---

src/Plugins/RunawayProcessKiller/NativeMethods.cs
src/Plugins/RunawayProcessKiller/RunawayProcessKiller.csproj
src/Plugins/RunawayProcessKiller/RunawayProcessKillerExtension.cs
src/Test/winswTests/Extensions/RunawayProcessKillerTest.cs

Fixes #237 
Based on #356 
I'll see if I can eliminate the duplication another day.

Fix RunawayProcessKiller

---

.gitignore
Directory.Build.props
WinSW.nuspec
appveyor.yml
src/Core/ServiceWrapper/winsw.csproj

Fixes #382, https://github.com/kohsuke/winsw/issues/378#issuecomment-578535632
~Removes "deployment name"s since they are not used in GitHub Releases deployment.~

Produce ready-to-publish artifacts in build phase for AppVeyor

---

src/Core/WinSWCore/LogAppenders.cs
src/Core/WinSWCore/Util/ProcessHelper.cs

Stop buffering stdout/stderr

---

src/Core/ServiceWrapper/Main.cs
src/Core/WinSWCore/ServiceDescriptor.cs

Closes #250 
A stack trace always means program defect.

Don't print stack trace to console for user errors

---

src/Test/winswTests/Extensions/RunawayProcessKillerTest.cs

Fixes https://github.com/kohsuke/winsw/pull/359#issuecomment-580928300
Debugging showed that two read operations can get different process parameters and environment block addresses. This may be because we read them too early before the process is fully initialized.

Potentially fix RunawayProcessKillerTest

---

src/Core/ServiceWrapper/Main.cs

Improve CLI behaviors with empty arguments

---

appveyor.yml

Work item #378 
Please add `patch: true` in release job configuration.

Disable version patching in the CI run

---

appveyor.yml

`Debug` configuration triggers assertions and helps diagnose test failures.

Add Debug configuration

---

src/Core/WinSWCore/Download.cs

Enable TLS 1.1/1.2 when using .NET2 and .NET4 packages on Windows 7 and Windows Server 2008 R2

---

src/Core/ServiceWrapper/Main.cs
src/Core/WinSWCore/Download.cs
src/Core/WinSWCore/LogAppenders.cs
src/Core/WinSWCore/Util/FileHelper.cs

Implement atomic file movement

---

src/Core/WinSWCore/Util/FileHelper.cs

Throw correct exceptions for IO errors

---

Directory.Build.targets
src/Core/WinSWCore/WinSWCore.csproj

Temporary fix for #411 
Quite disappointed.

Disable MMI

---

src/Core/ServiceWrapper/Main.cs

Revert CLI behaviors in non-interactive mode

---

LICENSE.txt

GitHub isn't clever enough to recognize our license.

Update license for GitHub

---

WinSW.nuspec

https://docs.microsoft.com/nuget/reference/nuspec#licenseurl
https://docs.microsoft.com/nuget/reference/nuspec#license

Fix NuGet warning

---

.github/CODEOWNERS

I an use a team or setup individual review requests. What would you prefer @NextTurn ?

Update CODEOWNERS to request reviews from all maintainers

---

CHANGELOG.md
README.md
WinSW.nuspec

subj. We need to update the locations, mostly for housekeeping purposes

Update the repository locations in Documentation and the NuGet spec

---

src/Core/WinSWCore/Download.cs

Supersedes #280
If this is to be an opt-out behavior, here are some proposed XML attribute names:
- `preserveNewest`
- `updateIfNewer`
- `skip(if)Unchanged`/`skip(if)Unmodified`/`skipIfNotMidified`

Support 'If-Modified-Since' for downloads

---

src/Core/ServiceWrapper/Main.cs
src/Core/WinSWCore/Native/Advapi32.cs

Set description via advapi32

---

CONTRIBUTING.md
DEVELOPER.md

The basic idea is that people don't have to install Visual Studio (although it's recommended).
VS Code is the mostly used open source code editor in .NET community so I don't consider it as an ad.

Initialize contributing guidelines

---

.github/ISSUE_TEMPLATE/1-feature-request.md
.github/ISSUE_TEMPLATE/2-bug-report.md
.github/ISSUE_TEMPLATE/3-documentation.md
.github/ISSUE_TEMPLATE/4-question.md
.github/ISSUE_TEMPLATE/config.yml

I took some templates from my other projects. Styling could be aligned better, but I would like to start with something.
Fixes #412

Create Issue templates

---

src/Core/WinSWCore/Util/XmlHelper.cs

Annotate for NRT

---

CHANGELOG.md
README.md
doc/deferredFileOperations.md
doc/exeConfigFile.md
doc/extensions/extensions.md
doc/extensions/runawayProcessKiller.md
doc/extensions/sharedDirectoryMapper.md
doc/installation.md
doc/loggingAndErrorReporting.md
doc/selfRestartingService.md
doc/xmlConfigFile.md

- Promotes header levels.
- Uses sentence-style capitalization. https://docs.microsoft.com/style-guide/capitalization

Update documentation headers

---

doc/xmlConfigFile.md

Contributes to #444 
Resolves #121 
DISCLAIMER: I'm not a developer of Windows and it's not my responsibility to point to all the details of Windows.
So I recommend this site for you:
https://docs.microsoft.com/windows/win32/services/services
---
The `LocalService` account is preferred but it may cause permission problems for beginners.

Document special accounts and the default domain

---

eng/build.yml
eng/release.yml

Use variable group in pipelines

---

src/Core/ServiceWrapper/winsw.csproj
src/Core/WinSWCore/WinSWCore.csproj
src/Plugins/RunawayProcessKiller/RunawayProcessKiller.csproj
src/Plugins/SharedDirectoryMapper/SharedDirectoryMapper.csproj
src/Test/winswTests/winswTests.csproj

Fixes #488
Contributes to #493

Fix versioning of WinSW builds

---

eng/release.yml

This build will trigger a new release once finished...

Disable PR trigger in release builds

---

src/Test/winswTests/Util/ProcessHelperTest.cs

Skip the failing process helper test

---

Directory.Build.targets
src/Core/WinSWCore/Util/ProcessHelper.cs
src/Core/WinSWCore/WinSWCore.csproj
src/Core/WinSWCore/Wmi.cs

Remove dead codes

---

src/Core/WinSWCore/Configuration/DefaultSettings.cs

Fix default working directory on .NET Core

---

src/Core/ServiceWrapper/Main.cs

Ensure event source is registered during installation

---

doc/xmlConfigFile.md

Remove locale from docs.ms link

---

doc/loggingAndErrorReporting.md

I've filed a motion to remove them.

Warn about broken settings

---

doc/xmlConfigFile.md

Note about the "incremental download" feature

---

src/Core/ServiceWrapper/Main.cs
src/Core/ServiceWrapper/Properties/AssemblyInfo.cs
src/Test/winswTests/Configuration/ExamplesTest.cs
src/Test/winswTests/DownloadConfigTests.cs
src/Test/winswTests/DownloadTests.cs
src/Test/winswTests/MainTest.cs
src/Test/winswTests/Util/AsyncAssert.cs
src/Test/winswTests/Util/DateTimeExtensions.cs
src/Test/winswTests/Util/TestHelper.cs

Sets up a simple HTTP listener for testing. Hope it works.

Increase code coverage

---

doc/xmlConfigFile.md
examples/sample-allOptions.xml
src/Core/ServiceWrapper/Main.cs
src/Core/WinSWCore/Configuration/DefaultSettings.cs
src/Core/WinSWCore/Configuration/IWinSWConfiguration.cs
src/Core/WinSWCore/ServiceDescriptor.cs

As per *sample-allOptions.xml*.
Fixes #226 
Closes #291 - nothing to do

Support <startarguments> and <stoparguments>

---

eng/build.yml
src/NuGet.config

Fixes #549
A generic and permanent solution.

Add NuGet.config

---

eng/build.yml

Breaking changes and crazy ideas that may or may not get into releases.

WinSW v3 test plan

---

src/Core/ServiceWrapper/WrapperService.cs
src/Core/WinSWCore/Native/Libraries.cs
src/Core/WinSWCore/Native/ProcessApis.cs
src/Core/WinSWCore/Util/ProcessHelper.cs
src/Core/WinSWCore/WinSWCore.csproj
src/Plugins/RunawayProcessKiller/RunawayProcessKillerExtension.cs
src/Test/winswTests/Extensions/RunawayProcessKillerTest.cs

Remove dependency on Win32_Process

---

src/Core/WinSWCore/Util/ProcessHelper.cs
src/Test/winswTests/Util/FilesystemTestHelper.cs
src/Test/winswTests/Util/ProcessHelperTest.cs

That test didn't cover the code paths, but it gave you a lot of confidence?

Avoid setting current process environment variables

---

src/Core/WinSWCore/Util/ProcessHelper.cs

Check start time of possible child processes

---

src/WinSW.Core/CommandException.cs
src/WinSW.Core/Native/Security.cs
src/WinSW.Core/Native/Service.cs
src/WinSW.Core/Native/Throw.cs
src/WinSW/Program.cs

Improve exception logging

---

src/WinSW.Core/LogAppenders.cs

Async I/O is threadless - there is no blocking thread waiting for I/O completions.

Replace threads with tasks

---

src/WinSW.Core/Util/ProcessHelper.cs
src/WinSW/WrapperService.cs

Fixes #174
Fixes #262
Fixes #304
Please submit a new issue if you still see "Finished" immediately after "Stopping".

Fix termination

---

src/WinSW.Core/FormatExtensions.cs
src/WinSW.Core/LogAppenders.cs
src/WinSW.Core/Util/ProcessHelper.cs
src/WinSW/Logging/WrapperServiceEventLogProvider.cs
src/WinSW/WrapperService.cs

Fixes #189
Fixes #198
Fixes #265

Catch all exceptions

---

src/WinSW.Core/Native/Service.cs
src/WinSW.Core/Native/ServiceApis.cs
src/WinSW/Program.cs

Contributes to #256 
Contributes to #297

Add `refresh` command

---

samples/sample-complete.xml
samples/sample-minimal.xml
src/WinSW.Core/Configuration/DefaultSettings.cs
src/WinSW.Core/ServiceDescriptor.cs
src/WinSW.Tests/Configuration/ExamplesTest.cs
src/WinSW.Tests/Util/ServiceDescriptorAssert.cs
src/WinSW/Program.cs

Make `<name>` and `<description>` optional

---

docs/xml-config-file.md
src/WinSW.Core/ServiceDescriptor.cs
src/WinSW.Tests/ServiceDescriptorTests.cs

Remove `<*argument>`

---

src/WinSW.Core/Util/ProcessHelper.cs
src/WinSW/WrapperService.cs

Fixes #128
Contributes to #606
Marking as a bug because it harmed the UX.

Leave STDIN open

---

src/WinSW.Core/Configuration/DefaultSettings.cs
src/WinSW.Core/Native/Service.cs
src/WinSW.Core/NullableAttributes.cs
src/WinSW.Core/ServiceDescriptor.cs
src/WinSW.Core/Util/ProcessHelper.cs
src/WinSW/Logging/IServiceEventLog.cs
src/WinSW/Logging/IServiceEventLogProvider.cs
src/WinSW/Logging/ServiceEventLogAppender.cs
src/WinSW/Logging/WrapperServiceEventLogProvider.cs
src/WinSW/NullableAttributes.cs
src/WinSW/Program.cs
src/WinSW/WrapperService.cs

Fixes #489 
The Event Log service is available during the preshutdown period.

Preshutdown support

---

src/WinSW.Core/Native/Service.cs
src/WinSW.Core/Native/ServiceApis.cs
src/WinSW.Core/Util/ProcessExtensions.cs
src/WinSW/Program.cs

```
└─explorer (7000)
├─pwsh (17412)
│  ├─conhost (10772)
│  └─cmd (9868)
│     └─WinSW (8512)
└─devenv (5608)
├─MSBuild (15960)
│  └─conhost (18340)
├─PerfWatson2 (11692)
├─ScriptedSandbox64 (15100)
└─Microsoft.ServiceHub.Controller (3024)
├─ServiceHub.RoslynCodeAnalysisService32 (28424)
│  └─conhost (27060)
├─ServiceHub.Host.CLR.x86 (20880)
│  └─conhost (24680)
├─ServiceHub.Host.CLR.x86 (27496)
│  └─conhost (19888)
├─ServiceHub.SettingsHost (2372)
│  └─conhost (6844)
├─ServiceHub.DataWarehouseHost (17928)
│  └─conhost (5484)
├─ServiceHub.IdentityHost (15708)
│  └─conhost (22548)
├─ServiceHub.ThreadedWaitDialog (25168)
│  └─conhost (22500)
├─conhost (28572)
├─ServiceHub.TestWindowStoreHost (13860)
│  ├─conhost (4064)
│  └─vstest.console (24604)
│     └─conhost (18764) …
```

Add `dev ps` command

---

src/WinSW/WrapperService.cs

Allow `<stopexecutable>` without arguments

---

src/WinSW.Core/LogAppenders.cs
src/WinSW.Core/Util/ProcessExtensions.cs
src/WinSW.Core/Util/SignalHelper.cs
src/WinSW/WrapperService.cs

Both #241 and #278 were complaining about excessive event log entries. There are a lot less now.
Feel free to send another request if these are still too many.

Reduce event log entries

---

src/WinSW.Core/Configuration/ProcessCommand.cs
src/WinSW.Core/Configuration/SettingNames.cs
src/WinSW.Core/Configuration/XmlServiceConfig.cs
src/WinSW.Core/LogAppenders.cs
src/WinSW.Tests/ServiceConfigTests.cs
src/WinSW/WrapperService.cs

Add stdout/stderr path settings

---

src/WinSW.Tasks/Trim.cs
src/WinSW.Tasks/WinSW.Tasks.csproj
src/WinSW.Tests/MetadataTests.cs
src/WinSW.Tests/WinSW.Tests.csproj
src/WinSW.sln
src/WinSW/WinSW.csproj

Trims the merged assembly. I probably missed something, but it's working properly.
610 KB merge -> 961 (+351) KB trim -> 656 (-305) KB
610 KB trim -> 446 (-164) KB merge -> 656 (+210) KB

Update .NET Framework packaging

---

src/WinSW/Program.cs

I'd say this is over engineering.

Remove `--timeout` option

---

CONTRIBUTING.md
MANIFEST.md
README.md
docs/cli-commands.md
docs/deferred-file-operations.md
docs/extensions/extensions.md
docs/extensions/shared-directory-mapper.md
docs/installation.md
docs/logging-and-error-reporting.md
docs/migrate-to-3-x.md
docs/self-restarting-service.md
docs/xml-config-file.md
samples/sample-complete.xml
samples/sample-minimal.xml
src/WinSW.Tests/ServiceConfigTests.cs

Revise docs for 3.0.0-alpha.3

---

eng/build.yml
src/WinSW.Core/Configuration/ServiceConfig.cs
src/WinSW.Core/Download.cs
src/WinSW.Core/WinSW.Core.csproj
src/WinSW.Plugins/WinSW.Plugins.csproj
src/WinSW.Tests/WinSW.Tests.csproj
src/WinSW/Program.cs
src/WinSW/WinSW.csproj
src/WinSW/WrapperService.cs

*WinSW.NETCore.x64.exe:* 35 MB -> 26.7 MB
*WinSW.NETCore.x64.zip:* 15.3 MB -> 11.7 MB

Upgrade to .NET 5

---

src/Core/WinSWCore/Configuration/YamlConfiguration.cs
src/Test/winswTests/ServiceDescriptorYamlTest.cs

This PR includes Unit Test coverage for YAML configuration parsing.

YAML config test coverage

---

src/Core/WinSWCore/Extensions/WinSWExtensionManager.cs

Case-insensitive search for type name

---

src/WinSW.Core/Util/ProcessHelper.cs
src/WinSW.Core/Util/SignalHelper.cs
src/WinSW/WrapperService.cs

Back-ports #643
@oleg-nenashev I hope bug fixes can be merged as soon as possible.

Fix service crashes

---

doc/yamlConfigFile.md

- Add the phase 3 demo link to the yamlConfig.md

Update YAML configuration documentation

---

eng/build.yml
src/WinSW/WinSW.csproj

Fixes *WinSW.NETCore.x64/x86.exe*

Fix single-file apps

---

eng/build.yml
src/WinSW.Core/Util/XmlHelper.cs

This doesn't work for most users.

Drop WinSW.NETCore31.zip

---

src/WinSW/Program.cs

Redirect I/O of elevated process

---

docs/xml-config-file.md
src/WinSW/Program.cs

Revise docs for 3.0.0-alpha.6

---

src/WinSW.Core/Configuration/XmlServiceConfig.cs
src/WinSW.Tests/ServiceConfigTests.cs

https://github.com/winsw/winsw/issues/530#issuecomment-730948222
/cc mightybeaker

Fix XML queries

---

src/WinSW/Program.cs

|3.x|2.x|
|-|-|
|Active|Started|
|Inactive|Stopped|

Distinguish service status as active or inactive

---

src/WinSW.Core/Native/ConsoleApis.cs
src/WinSW/WrapperService.cs

Set console output code page to UTF-8

---

src/WinSW.Core/LogAppenders.cs
src/WinSW.Tests/LogAppenderTests.cs

Tweak stdout/stderr redirections

---

src/WinSW.Core/Native/ConsoleApis.cs
src/WinSW.Core/Native/ConsoleEx.cs
src/WinSW.Core/Native/Credentials.cs
src/WinSW.Core/Native/FileApis.cs
src/WinSW.Core/Native/Handle.cs
src/WinSW.Core/Native/ProcessApis.cs
src/WinSW.Core/Native/Security.cs
src/WinSW/Program.cs

Enhance console prompting

---

src/WinSW.Core/PeriodicRollingCalendar.cs

Allow rotating logs monthly

---

doc/xmlConfigFile.md

Remove `<*argument>` from docs

---

eng/build.yml
src/WinSW.Core/Download.cs
src/WinSW.Core/WinSW.Core.csproj
src/WinSW.Plugins/WinSW.Plugins.csproj
src/WinSW.Tests/WinSW.Tests.csproj
src/WinSW/WinSW.csproj

This reverts commit 6db5fbc2c3943cf0f39e5c9780409fa850c121e1.

Revert "Upgrade to .NET 6 (#806)"

---

Directory.Build.props
eng/build.yml
src/WinSW.Core/Download.cs
src/WinSW.Core/WinSW.Core.csproj
src/WinSW.Plugins/WinSW.Plugins.csproj
src/WinSW.Tests/WinSW.Tests.csproj
src/WinSW/WinSW.csproj

Revert "Revert "Upgrade to .NET 6 (#806)""

---

src/WinSW.Core/Download.cs
src/WinSW.Core/WrapperService.cs
src/WinSW.Tests/DownloadTests.cs

Fix download exceptions when ignoring errors

---

docs/xml-config-file.md

Add missing / to service account block.

Update xml-config-file.md - Add missing `/` to service account block.

---

samples/complete.xml

Seems like someone's editor replaced some quotation marks.
This caused issues when I tried to use the sample as a template. :)

Fix incorrect quotation marks

---

docs/xml-config-file.md

Fix closing tag in the configuration sample
