winsw.csproj, winsw.sln
* Win32 is the only supported configurationdue to Win32 API dependencies
* Debug and Release now output the data to different folders
Fixes #84
Signed-off-by: Oleg Nenashev <o.v.nenashev@gmail.com>
=> Get rid of extra configurations, fix output destinations

src/Core/ServiceWrapper/Main.cs, src/Core/ServiceWrapper/packages.config, src/Core/ServiceWrapper/winsw.csproj, src/packages/repositories.config
DONE: 
* Integrate log4net into WinSW, migrate wrapper.log engine
TODOs:
* Migrate EventLogs to log4net
* Delegate exceptions handling to log4net
* Allows setting up log levels from ServiceDescriptor
* (?) Migrate STDERR/STDOUT logs to log4net
* (?) Support XML configurations of log4net loggers
Signed-off-by: Oleg Nenashev <o.v.nenashev@gmail.com>
=> Migration of logging handlers to log4net (#69)

README.markdown
'allowservicelogon' in the note wasn't displaying due to the xml tags.
=> README: Escape allowservicelogon tags

src/Core/ServiceWrapper/Main.cs, src/Core/ServiceWrapper/winsw.csproj, src/Core/WinSWCore/Extensions/AbstractWinSWExtension.cs, src/Core/WinSWCore/Extensions/IWinSWExtension.cs, src/Core/WinSWCore/Extensions/WinSWExtensionManager.cs, src/Core/WinSWCore/ServiceDescriptor.cs, src/Core/WinSWCore/Util/ProcessHelper.cs, src/Core/WinSWCore/Util/SigIntHelper.cs, src/Core/WinSWCore/Util/XmlHelper.cs, src/Core/WinSWCore/WinSWCore.csproj, src/Core/WinSWCore/WinSWSystem.cs, src/Plugins/RunawayProcessKiller/Properties/AssemblyInfo.cs, src/Plugins/RunawayProcessKiller/RunawayProcessKiller.csproj, src/Plugins/RunawayProcessKiller/RunawayProcessKillerExtension.cs, src/Plugins/RunawayProcessKiller/packages.config, src/Plugins/RunawayProcessKiller/sampleConfig.xml, src/Test/winswTests/Extensions/RunawayProcessKillerTest.cs, src/packages/repositories.config, src/winsw.sln
Addresses #125. Changes summary:
This change introduces an extension, which performs automatic termination of runaway processes on startup. Sample configuration:
```
﻿<?xml version="1.0" encoding="utf-8" ?>
<service>
<id>SERVICE_NAME</id>
<name>Jenkins Slave</name>
<description>This service runs a slave for Jenkins continuous integration system.</description>
<executable>%BASE%\sleep.bat</executable>
<arguments></arguments>
<logmode>rotate</logmode>
<extensions>
<extension enabled="true" className="winsw.Plugins.RunawayProcessKiller.RunawayProcessKillerExtension" id="killOnStartup">
<pidfile>%BASE%\pid.txt</pidfile>
<stopTimeout>5000</stopTimeout>
<stopParentFirst>false</stopParentFirst>
</extension>
</extensions>
</service>
```
https://issues.jenkins-ci.org/browse/JENKINS-39231
=> [Issue #125] Runaway process termination on startup

.gitignore, README.md, appveyor.yml, doc/extensions/extensions.md, sign.sh, src/Core/ServiceWrapper/winsw.csproj, src/Core/WinSWCore/WinSWCore.csproj, src/Plugins/RunawayProcessKiller/RunawayProcessKiller.csproj, src/Plugins/SharedDirectoryMapper/SharedDirectoryMapper.csproj, src/Test/winswTests/Extensions/ExtensionTestBase.cs, src/Test/winswTests/Extensions/RunawayProcessKillerTest.cs, src/Test/winswTests/Extensions/SharedDirectoryMapperTest.cs, src/Test/winswTests/NunitTest.nunit, src/Test/winswTests/packages.config, src/Test/winswTests/winswTests.csproj, winsw.csproj
Finally I decided to try Appveyor before using VS Team Services.
The draft project is available here: https://ci.appveyor.com/project/oleg-nenashev/winsw
TODOs:
=> Fixes #142 - Deploy the automatic build on Appveyor

README.md, appveyor.yml, src/Core/ServiceWrapper/winsw.csproj, src/Core/ServiceWrapper_dotNET4/Main.cs, src/Core/ServiceWrapper_dotNET4/Properties/AssemblyInfo.cs, src/Core/ServiceWrapper_dotNET4/packages.config, src/Core/ServiceWrapper_dotNET4/winsw_dotNET4.csproj, src/winsw.sln
According to the requests, it is not always convenient to declare the `.NET Framework 4` support in `exe.config`. Such approach also does not guarantee that the executable is really operational in this framework.
This PR adds a new project, which generates a binary targeting `.NET Framework 4.0`.
Addresses #103, #112, ant #102
@reviewbybees
=> Provide the new .NET4-compatible executable

appveyor.yml, src/Core/ServiceWrapper/Properties/AssemblyInfo.cs, src/Core/ServiceWrapper/pom.xml, src/Core/WinSWCore/Properties/AssemblyInfo.cs, src/Plugins/RunawayProcessKiller/Properties/AssemblyInfo.cs, src/Plugins/SharedDirectoryMapper/Properties/AssemblyInfo.cs, src/Test/winswTests/Properties/AssemblyInfo.cs
=> Setup proper assembly versions

appveyor.yml
In order to maintain Release and Snapshot versions on AppVeyor, I had to create two separate jobs on it. These jobs utilise the same config, but actually they only specify different version formats.
* Release job: `2.0.{build}`
* Snapshot & PR builder: 2.0-SNAPSHOT-build{build}
Maybe it's not the best practice
=> Handover Version control to AppVeyor jobs

src/Core/ServiceWrapper/Main.cs, src/Core/WinSWCore/Extensions/WinSWExtensionManager.cs
Due to the lack of logging on the top level, particular issues in WinSW cause failure without any message in system and event logs. This PR improves logging a bit.
Fixes #134
=> Improve handling of initialization errors

appveyor.yml
=> AppVeyor Builder generalization

pom.xml
Add support of Maven releases for the 2.0 release
Fixes #80
=> Maven POM update towards 2.0 

src/Core/ServiceWrapper/Main.cs
This change does not change the behavior (return code, etc.) of the WinSW logic, but on the other hand it provides diagnostic information.
Since 2.0 is approaching, I would appreciate feedback regarding changing the default behavior. I would rather implement a `uninstall!` command, which stops the running service and fails horrible if the service cannot be deleted. But maybe it's more convenient to have a breaking change
@reviewbybees
=> Issue #146 - Improve logging of the Uninstall Operation.

README.md, src/Core/WinSWCore/Util/ProcessHelper.cs
Sometimes we get an InvalidOperationException when we kill a process that is already dead and other times we get a Win32Exception. Let's ignore all exceptions from killing a process if it has exited.
Additionally, ArgumentException is the wrong exception to catch. I have never seen Process.Kill() throw that. It seems to be a bad copy and paste from line 50.
=> Do not propagate exceptions from Process.Kill() if the process actually exits

src/Core/WinSWCore/Util/ProcessHelper.cs
Addresses #59 and [JENKINS-22692](https://issues.jenkins-ci.org/browse/JENKINS-22692)
This is a bit hackish way, which still terminates the spawned process even in the case of the ongoing system shutdown. In Jenkins project it should help with enforced termination of Windows agents, which somehow leaves hanging connections on the master side. Maybe this issue has been already solved in other way on the remoting side, but there is no confirmations from users....
@reviewbybees
=> Issue #59 - Prevent failure when Child processes cannot be retrieved due to the system shutdown

src/Core/ServiceWrapper/Main.cs
See #54. @kenny-evitt was concerned about dumping of environment variables from the XML config file to the Event Log since they may contain secrets. I do not see much sense in writing such information to the event log, so I've decided to disable such logging at all in WinSW 2.0.
CC @daniel-beck as a Jenkins security officer.
@reviewbybees
=> Fixes #54. Do not dump WinSW environment variables to the Event log

src/Core/ServiceWrapper/winsw.csproj, src/Core/WinSWCore/Util/ProcessHelper.cs, src/Core/WinSWCore/Util/SigIntHelper.cs
Java application and child conhost process should both gracefully shut down, without kill or warnings. Changelist description below.
Detach from console process after sending SIGINT to java.
Note: we still need `<stopparentprocessfirst>` to be set to true, so the
parent (java) process is shut down first.
Moved exception handling to GetChildPids.
StopProcessAndChildren now gets a fresh list of childPids after stopping
a parent process, as that may have caused some child processes to
terminate.
=> Fixes #95 - Service not sending SIGINT properly to java

src/Core/ServiceWrapper/Main.cs, src/Core/WinSWCore/Util/ProcessHelper.cs, src/Plugins/RunawayProcessKiller/RunawayProcessKillerExtension.cs, src/Test/winswTests/Extensions/ExtensionTestBase.cs, src/Test/winswTests/Extensions/RunawayProcessKillerTest.cs, src/Test/winswTests/Util/ConfigXmlBuilder.cs, src/Test/winswTests/Util/FilesystemTestHelper.cs, src/Test/winswTests/Util/ProcessHelperTest.cs, src/Test/winswTests/winswTests.csproj
This change intends fixing the regression I've introduced in WinSW 2.0 in https://github.com/kohsuke/winsw/commit/92367f44ef208bca20c6dfcadb975722fd28763d. I have added `ps.EnvironmentVariables[WinSWSystem.ENVVAR_NAME_SERVICE_ID.ToLower()] = _descriptor.Id;`, which made all variables to be in lowercase in the injected process. Some tools were not ready to that though they are expected to handle Env Vars in the case-insensitive mode in Windows. But Java tools do not do that By default, hence [JENKINS-42744](https://issues.jenkins-ci.org/browse/JENKINS-42744) was reported by Jenkins users.
Changes:
https://issues.jenkins-ci.org/browse/JENKINS-42744
@reviewbybees
=> [JENKINS-42744] - Prevent conversion of environment variables to lowercase

doc/xmlConfigFile.md, examples/sample-allOptions.xml, src/Core/WinSWCore/Download.cs
This code adds authentication handling for downloads from  a server
which requires this. [Source](http://stackoverflow.com/questions/5572588/webrequest-getresponse-is-throwing-error-401-unauthorized).
I tested the functionality with a Jenkins instance using the plugin "HTTP Header by reverse proxy" and an Apache 2.4 with Kerberos authentication (mod_auth_kerb 5.4). Another check was to "disable" any authentication that no credentials were required (Apache "Require all granted").
The service was created on Windows server 2008 with bind to a domain account.
=> Issue #126 - Add support of authentication in the download settings

doc/xmlConfigFile.md, src/Core/ServiceWrapper/Main.cs, src/Core/WinSWCore/Download.cs, src/Test/winswTests/DownloadTest.cs, src/Test/winswTests/Util/ConfigXmlBuilder.cs, src/Test/winswTests/winswTests.csproj
This change allows preventing the executable start if the requested file cannot be downloaded. It also adds logging of download operations to the wrapper log.
The approach still needs to be finalized, because `FailOnError` does not propagate errors to the `start` command (as all other similar commands)
CC @nightman68 I just decided to write it in order to provide an example. If you want, I can integrate your auth proposals in the same way.
=> Introduce the Download#FailOnError option.

doc/xmlConfigFile.md, examples/sample-allOptions.xml, src/Core/WinSWCore/Download.cs, src/Core/WinSWCore/ServiceDescriptor.cs, src/Core/WinSWCore/Util/XmlHelper.cs, src/Test/winswTests/DownloadTest.cs, src/Test/winswTests/Util/ConfigXmlBuilder.cs, src/Test/winswTests/Util/ExceptionHelper.cs, src/Test/winswTests/winswTests.csproj
This PR finalizes #126, which includes #194 from @nightman68 and #195 from me.
=> Finalize the Download Command changes

doc/xmlConfigFile.md, examples/sample-allOptions.xml, src/Core/ServiceWrapper/Main.cs, src/Core/WinSWCore/Configuration/DefaultSettings.cs, src/Core/WinSWCore/Native/Advapi32.cs, src/Core/WinSWCore/ServiceDescriptor.cs, src/Test/winswTests/ServiceDescriptorTests.cs, src/Test/winswTests/Util/ConfigXmlBuilder.cs
Fixes #183 . The only problem is that MMC and Service are too smart and cache the option internally (see [this article](https://social.msdn.microsoft.com/Forums/en-US/e5dbfe02-5125-4833-8e6b-3aa3d8518fc8/delayed-start-registry-setting?forum=biztalkgeneral)), so the setting does not get displayed there until the system restart.
CC @mtman
=> #183 - Add core logic for the DelayedStart option support

src/Core/ServiceWrapper/packages.config, src/Core/ServiceWrapper/winsw.csproj, src/Core/ServiceWrapper_dotNET4/packages.config, src/Core/ServiceWrapper_dotNET4/winsw_dotNET4.csproj, src/Core/WinSWCore/WinSWCore.csproj, src/Core/WinSWCore/packages.config, src/Plugins/RunawayProcessKiller/RunawayProcessKiller.csproj, src/Plugins/RunawayProcessKiller/packages.config, src/Plugins/SharedDirectoryMapper/SharedDirectoryMapper.csproj, src/Plugins/SharedDirectoryMapper/packages.config, src/Test/winswTests/packages.config, src/Test/winswTests/winswTests.csproj
It effectively bumps the bundled log4net version from 1.2.13 to 2.0.8 (log4net NuGet package used to have different versions). According to the changelogs, there is no expected compatibility issues: 
log4net changelog: https://logging.apache.org/log4net/release/release-notes.html
Addresses #148
=> Issue #148 - Update log4net to 2.0.8

src/Core/ServiceWrapper/Main.cs, src/Test/winswTests/MainTest.cs
Addresses #206, regression in 2.0 since it breaks the documented behavior. This is rather a workaround to prevent printing of log messages in CLI with the default logging level. 
I do not consider it as final fix. Ideally WinSW startup logic should determine commands like `status` and disable console log appender for them at all. It requires extra changes in the code.
@reviewbybees @Digital-Chaos
=> [Issue #206] - Prevent printing of logs in the status command

DEVELOPER.md, README.md
This guide describes how to build, test and release WinSW. More documentation never hurts, especially since I want to avoid a single-person bottleneck.
@reviewbybees @kohsuke
=> Add WinSW Developer Guide

src/Core/ServiceWrapper/Main.cs, src/Core/WinSWCore/Util/ProcessHelper.cs
It restores logging of executables, which has been broken in https://github.com/kohsuke/winsw/pull/220.
Not a regression, because the change has not been released yet. 
It is not a full fix, I still need to determine why it causes a preliminary service exit in the case of the infinite ping executable. 
CC @pnikonowicz
=> Issue #218 - ProcessHelper#StartProcessAndCallbackForExit() should redirect STDOUT/STDERR when LogHandler is defined

src/Plugins/RunawayProcessKiller/RunawayProcessKillerExtension.cs
See #237. The change adds some extra diagnostics, which may help to determine if we kill the right process. 
For more hardening, I could also add the executable name check. After such change WinSW will ignore Runaway processes if the executable name changes. This is not a real case IMHO.
@Thomehack @reviewbybees
=> Issue #237 - Improve diagnostics of the Runaway Process Killer when it kills the process

src/Test/winswTests/Extensions/RunawayProcessKillerTest.cs
This way the check can be reenabled as well.
=> Fix environment variable setting in RunawayProcessKiller test

src/Core/ServiceWrapper/Main.cs, src/Core/WinSWCore/Configuration/DefaultSettings.cs, src/Core/WinSWCore/Configuration/IWinSWConfiguration.cs, src/Core/WinSWCore/ServiceDescriptor.cs, src/Core/WinSWCore/Util/ProcessHelper.cs
adds a `<hidewindow>true</hidewindow>` config switch
so that launching bat files on legacy machines
running Interactive Services Detection doesn't balk with horrid warnings.
default behaviour remains as before.
=> Add a new `hidewindow` option to suppress windows popup on legacy platforms

src/Core/WinSWCore/LogAppenders.cs
=> Prevent application crash when `roll-by-size-time` is enabled

Directory.Build.targets, appveyor.yml, src/Core/ServiceWrapper/Main.cs, src/Core/ServiceWrapper/winsw.csproj, src/Core/WinSWCore/DynamicProxy.cs, src/Core/WinSWCore/LogAppenders.cs, src/Core/WinSWCore/WinSWCore.csproj, src/Plugins/RunawayProcessKiller/RunawayProcessKiller.csproj, src/Plugins/SharedDirectoryMapper/SharedDirectoryMapper.csproj, src/Test/winswTests/Configuration/ExamplesTest.cs, src/Test/winswTests/Extensions/RunawayProcessKillerTest.cs, src/Test/winswTests/NunitTest.nunit, src/Test/winswTests/ServiceDescriptorTests.cs, src/Test/winswTests/Util/CLITestHelper.cs, src/Test/winswTests/Util/ExceptionHelper.cs, src/Test/winswTests/winswTests.csproj
Closes #337 
Closes #344 
Based on #353 
Is it a hard requirement that WinSW must be published as a single executable? It is possible to do that in .NET Core but it won't bring you any benefits.
This version is not ready for release.
=> Add new target frameworks: .NET 4.5, .NET Core win-x64, .NET Core win-x86 + Fix archiving of old logs in the `roll-by-size-time` mode

src/Core/WinSWCore/Configuration/DefaultSettings.cs
=> Fix executable path and XML config file resolution on .NET Core

Directory.Build.targets, src/Core/ServiceWrapper/Main.cs, src/Core/ServiceWrapper/winsw.csproj, src/Core/WinSWCore/Util/ProcessHelper.cs, src/Core/WinSWCore/WinSWCore.csproj, src/Core/WinSWCore/Wmi.cs, src/Core/WinSWCore/WmiSchema.cs
Conflicts with #357 
*System.Management* has been deprecated. There are such notes everywhere in the docs.
> **System.Management** was the original .NET namespace used to access WMI; however, the APIs in this namespace generally are slower and do not scale as well relative to their more modern **Microsoft.Management.Infrastructure** counterparts.
=> Migrate from `System.Management` to MMI

src/Core/ServiceWrapper/Main.cs
=> Treat ERROR_SERVICE_ALREADY_RUNNING as success for start command

src/Core/WinSWCore/LogAppenders.cs
Hold for #390 
stdout/stderr must be read or closed to unblock the child process' write operations.
=> Fix stdout/stderr redirection when log disabled

src/Core/ServiceWrapper/Main.cs
Closes #309 
The corresponding Windows API `ControlService` will return `ERROR_SERVICE_NOT_ACTIVE` instead.
=> Treat ERROR_SERVICE_CANNOT_ACCEPT_CTRL as success for stop command

README.md
Fixes #211 . Chat URL: : https://gitter.im/winsw/winsw. It is the most straightforward way to address the issue, but we can add a more comprehensive structure of chats (e.g. develoer and user chats). No strong opinion there 
CC @NextTurn
=> Add a Gitter chat for the project

WinSW.nuspec
Subj. Since we have an executable now, it is quite straightforward to publish it
=> Add .NET 4.6.1 executables to the NuGet package

src/Core/WinSWCore/DynamicProxy.cs, src/Core/WinSWCore/Wmi.cs
Based on #356 
This PR made large changes to two "public" classes. I'm assuming this is used as a console program so API changes are OK?
=> Optimize DynamicProxy

doc/xmlConfigFile.md, examples/sample-allOptions.xml, src/Core/ServiceWrapper/Main.cs, src/Core/WinSWCore/Native/Advapi32.cs, src/Core/WinSWCore/ServiceDescriptor.cs, src/Core/WinSWCore/WinSWCore.csproj
Fixes #329 
Hold for #392 
Possible property names:
- `<securtityDescriptor>`
- `<securtityDescriptorString>`
- `<securtityDescriptorSddl>`
- `<stringSecurtityDescriptor>`
=> Support security descriptor string

src/Core/WinSWCore/Configuration/DefaultSettings.cs, src/Core/WinSWCore/Configuration/IWinSWConfiguration.cs, src/Core/WinSWCore/ServiceDescriptor.cs
Fixes the bug mentioned in #121 
Closes #109 
I have no interest in blaming someone. Keep in mind the **NULL** in Windows docs refers to `NULL` in C, `nullptr` in C++, or `null` in C#/Java, etc.
=> Fix default domain name

.github/ISSUE_TEMPLATE/3-documentation.md
It does not render in Chrome due to whatever reason, hence I replaced it by unicode emoji
=> Issue templates: Fix the Documentation icon rendering

src/Core/ServiceWrapper/Main.cs, src/Test/winswTests/MainTest.cs
Believe it or not, this accelerates the start-up.
=> Split commands into functions

src/Core/WinSWCore/ServiceDescriptor.cs
Closes #238 
Closes #305 
Workaround for v2.
=> Ensure that environment variables are loaded before resolving configurations

src/Core/WinSWCore/Download.cs
See jenkinsci/windows-slave-installer-module#25 for background.
This should enable TLS 1.3 on newer Windows versions.
=> Enable system default TLS versions when targeting .NET Framework 4.6.1

src/Core/WinSWCore/Download.cs
See jenkinsci/windows-slave-installer-module#25 for background.
=> Enable strong cryptography when running .NET 2.0 and 4.0 binaries on .NET Framework 4.6

src/Core/WinSWCore/Util/ProcessHelper.cs
Fixes #169 
According to the docs:
> By default, the priority class of a process is NORMAL_PRIORITY_CLASS. Use the CreateProcess function to specify the priority class of a child process when you create it. If the calling process is IDLE_PRIORITY_CLASS or BELOW_NORMAL_PRIORITY_CLASS, the new process will inherit this class.
=> Always set process priority if specified

doc/installation.md
Binaries have not been signed (with a digital signature) since 2013 or so.
=> Remove offline mode section from installation guide

.gitignore, Directory.Build.props, generate-key.ps1, src/Core/ServiceWrapper/winsw.csproj, src/Core/WinSWCore/WinSWCore.csproj, src/Plugins/RunawayProcessKiller/RunawayProcessKiller.csproj, src/Plugins/SharedDirectoryMapper/SharedDirectoryMapper.csproj
Closes #435
~- Define `SIGN_ASSEMBLY` environment variable to `true` in release builds.~
~- Move key files to a subdirectory.~
We don't really strong-name assemblies at the moment.
=> Remove strong name signing

README.md
This change continues https://github.com/winsw/winsw/pull/458 and updates Wiki even further.:
* Documentation for release lines is removed. WinSW 2.x is 4 years old, and it is compatible with WinSW 1.x. I do not think we need to spend any space on that anymore
* Move supported platforms up, update the text to reflect the actual state
* Add Contributing section
=> Cleanup and restructure the README page

doc/exeConfigFile.md, doc/installation.md
- Removes v1-specific contents about *.exe.config*.
- Removes contents about manually configuring the service with the Service Control Manager and even the Registry Editor. Everything should have been fully configurable via the XML.
=> Revise the installation guide

doc/deferredFileOperations.md
Dangerous, a bad practice, not part of Windows features.
=> Remove content about renaming running executables

doc/xmlConfigFile.md, src/Core/WinSWCore/Download.cs, src/Test/winswTests/DownloadTest.cs
This PR can be helpful for #490.  You will not need to copy the proxy settings to the system account (that can cause errors in other applications); just modify the XML configuration file (manually or programmatically) and restart the service.
=> Support proxy attribute for download

src/Core/ServiceWrapper/Main.cs
- These `SetServiceStatus` calls always fail.
- `SignalShutdownComplete` doesn't need to be called `StopIt`.
- `SignalShutdownComplete` shall not be called before extensions shutdown complete.
=> Properly request additional time for shutdown when `<waithint>` is set

README.md, src/Core/ServiceWrapper/Main.cs
The command is useful in uninstall scenarios, when the service needs to be stopped first.
It's better than `net stop <serviceId>` because the new `stopwait` command doesn't need to specify the actual service ID. I.e. it allows to keep the service ID in one place rather than two (config XML and uninstall script)
=> Add stopwait command - same as stop, but waits until the service is actually stopped:

doc/extensions/runawayProcessKiller.md, doc/extensions/sharedDirectoryMapper.md, doc/installation.md, doc/loggingAndErrorReporting.md, doc/xmlConfigFile.md, examples/sample-allOptions.xml, src/Core/WinSWCore/LogAppenders.cs, src/Plugins/RunawayProcessKiller/sampleConfig.xml, src/Plugins/SharedDirectoryMapper/sampleConfig.xml, src/Test/winswTests/Extensions/RunawayProcessKillerTest.cs, src/Test/winswTests/Extensions/SharedDirectoryMapperTest.cs, src/Test/winswTests/ServiceDescriptorTests.cs, src/Test/winswTests/Util/CLITestHelper.cs
According to `examples/sample-allOptions.xml`, `<logmode>` has been replaced by `<log></log>`; so does `rotate`.
=> Fix outdated tag

src/Core/ServiceWrapper/Program.cs, src/Core/WinSWCore/Configuration/DefaultSettings.cs, src/Core/WinSWCore/Configuration/IWinSWConfiguration.cs, src/Core/WinSWCore/Native/Security.cs, src/Core/WinSWCore/ServiceDescriptor.cs, src/Test/winswTests/ServiceDescriptorTests.cs
Fixes #508 
> NOTE
> This is not the final design.
`<domain>` and `<user>` are removed. Use `<username>` instead.
=> Merge <domain> and <user> to support User Principal Name

.github/dependabot.yml
Adds Dependabot for NuGet dependencies. Let's see whether it will pick up the current format
=> Add a Dependabot configuration

src/Core/ServiceWrapper/Program.cs, src/Core/WinSWCore/Native/CredentialApis.cs, src/Core/WinSWCore/Native/Errors.cs, src/Core/WinSWCore/Native/Libraries.cs, src/Core/WinSWCore/ServiceDescriptor.cs
Implements https://github.com/winsw/winsw/issues/308#issuecomment-613181403.
> NOTE
> This is not a final design.
Adds a `<prompt>` element under `<serviceaccount>` to allow prompting for user name and/or password when either is missing.
```xml
<prompt>dialog|console</prompt>
```
/cc @MrGrymReaper @m8urnett @laguiz @il--ya who may be interested in this area. Please add a reaction to indicate that you want to be subscribed to further updates.
=> Allow prompting for credentials

doc/extensions/runawayProcessKiller.md, doc/xmlConfigFile.md, examples/sample-allOptions.xml, src/Core/ServiceWrapper/WrapperService.cs, src/Core/WinSWCore/Configuration/DefaultSettings.cs, src/Core/WinSWCore/Configuration/IWinSWConfiguration.cs, src/Core/WinSWCore/ServiceDescriptor.cs, src/Core/WinSWCore/Util/ProcessHelper.cs, src/Plugins/RunawayProcessKiller/RunawayProcessKillerExtension.cs, src/Plugins/RunawayProcessKiller/sampleConfig.xml, src/Test/winswTests/Extensions/RunawayProcessKillerTest.cs, src/Test/winswTests/ServiceDescriptorTests.cs, src/Test/winswTests/Util/ConfigXmlBuilder.cs
Fixes #95 
Fixes #115 
Fixes #123 
Fixes #245 
Fixes #283 
Fixes #295 
Verified that the Java shutdown hook is triggered with @lafual's codes in https://github.com/winsw/winsw/issues/283#issuecomment-401624379.
Stopping child processes first never ever works. **The Console Window Host (conhost.exe) does not have a console.** It's a host process for the console **window**.
---
~Closes #174~
~Closes #262~
~Closes #304~
This part was excluded from this PR.
---
https://github.com/winsw/winsw/issues/108#issuecomment-172876016
> actually writing a service is not rocket science
Writing a service is not rocket science, writing a service wrapper is, no?
=> Remove <stopparentprocessfirst> setting and fix process termination

eng/build.yml, src/WinSW/WinSW.csproj
Fixes #416 
Hold for #418 
Most users may not have the xxxx xxxx runtime installed. Therefore, I'm dropping the runtime-dependent archives and publish self-contained ones instead.
After #409 is implemented there will be no need to document which file should be renamed.
=> Publish self-contained archives

src/WinSW.Core/Configuration/SettingNames.cs, src/WinSW.Core/ServiceDescriptor.cs, src/WinSW.Tests/ServiceDescriptorTests.cs, src/WinSW/WinSW.csproj, src/WinSW/WrapperService.cs
Contributes to #256
Fixes #404
```xml
<service>
<prestart>
<executable>{prestartExecutable}</executable>
<arguments>{prestartArguments}</arguments>
</prestart>
<poststart>
<executable>{poststartExecutable}</executable>
<arguments>{poststartArguments}</arguments>
</poststart>
<prestop>
<executable>{prestopExecutable}</executable>
<arguments>{prestopArguments}</arguments>
</prestop>
<poststop>
<executable>{poststopExecutable}</executable>
<arguments>{poststopArguments}</arguments>
</poststop>
</service>
```
=> Add `prestart`/`poststart`/`prestop`/`poststop` settings

src/WinSW/WrapperService.cs
Removes duplicated warning/error entries.
=> Redirect event logging

src/WinSW.Core/Configuration/DefaultSettings.cs, src/WinSW.Core/Configuration/IWinSWConfiguration.cs, src/WinSW.Core/ServiceDescriptor.cs, src/WinSW.Tests/Util/ServiceDescriptorAssert.cs, src/WinSW/WrapperService.cs
*C:\Windows\System32\\* doesn't make much sense for most Windows apps. The default working directory of child processes is set to the executable directory since WinSW 1.12. This sets it for the wrapper as well, which allows the use of relative paths.
=> Set a default working directory for the wrapper

src/WinSW.Core/Native/ResourceApis.cs, src/WinSW.Core/Native/Resources.cs, src/WinSW.Core/Native/Throw.cs, src/WinSW.Tests/Configuration/ExamplesTest.cs, src/WinSW.Tests/MainTest.cs, src/WinSW.Tests/Util/Layout.cs, src/WinSW/Program.cs
Fixes #199
```
winsw customize -o <output> --manufacturer <manufacturer>
```
There is currently a limitation on the new name:
```cs
const int minLength = 12;
const int maxLength = 15;
```
/cc @aminjam
=> Add `customize` command

src/WinSW.Core/Util/ProcessExtensions.cs, src/WinSW.Tests/CommandLineTests.cs, src/WinSW/ServiceMessages.cs, src/WinSW/WrapperService.cs
```cs
Log.Debug("Sending Ctrl+C...");
if (!SetConsoleCtrlHandler(null, true))
throw new Win32Exception();
if (!GenerateConsoleCtrlEvent(CtrlEvents.CTRL_C_EVENT, 0))
throw new Win32Exception();
if (!SetConsoleCtrlHandler(null, false))
throw new Win32Exception();
bool succeeded = FreeConsole();
Debug.Assert(succeeded);
Log.Debug("Sent Ctrl+C.");
```
```cs
Assert.EndsWith(
ServiceMessages.StoppedSuccessfully + Environment.NewLine,
File.ReadAllText(Path.ChangeExtension(config.FullPath, ".wrapper.log")));
```
```
Error Message:
Assert.EndsWith() Failure:
Expected:    Service stopped successfully.
Actual:   ···430 DEBUG - Sending Ctrl+C...
```
=> Fix service crashes

src/Core/WinSWCore/Native/Security.cs, src/Core/WinSWCore/Native/SecurityApis.cs
=> Fix installation crashes when `allowservicelogon` is `true`

src/WinSW.Core/Configuration/XmlServiceConfig.cs, src/WinSW.Core/Native/RegistryApis.cs, src/WinSW.Core/Util/RegistryKeyExtensions.cs, src/WinSW.Core/WinSW.Core.csproj, src/WinSW/Program.cs
Fixes #256 
Contributes to #297 
Contributes to #606 
Automatically refreshes service properties if the config file is newer when the service is started or a command with write access is executed.
Enabled by default. Specify `<autoRefresh>false</autoRefresh>` to override.
The last write time of the registry key sometimes isn't updated (or is updated abnormally like the followings)... so you may end up with refreshing the service indefinitely.
```console
> WinSW.NET461.exe stop
file     last modified at 2020-08-15 3:39:23
registry last modified at 2020-08-15 3:25:44
03:39:27,053 - Service 'ABCD (ABC)' was refreshed successfully.
03:39:27,073 - Stopping service 'ABCD (ABC)'...
03:39:27,077 - Service 'ABCD (ABC)' has already stopped.
> WinSW.NET461.exe stop
file     last modified at …
```
=> Auto refresh

src/WinSW/WinSW.csproj
Continued from #651
*WinSW.NETCore.x64.exe:* 27.2 MB -> 15.6 MB
*WinSW.NETCore.x64.zip:* 11.8 MB -> 6.92 MB
=> Enable member-level trimming

src/WinSW.Core/Native/Handle.cs, src/WinSW.Core/Native/ProcessApis.cs, src/WinSW.Core/Util/ProcessExtensions.cs, src/WinSW/Program.cs
A `Process` object not started by us doesn't keep the handle.
=> Improve ProcessExtensions

src/WinSW.Core/Native/Service.cs
Previously, this code would close the Service Control Manager (SCM)
handle instead of the service handle, meaning:
- any future calls to the SCM would fail due to invalid handle
- a handle to the service was left open in error
Also, reduce the access rights given to the handle, as we don't need
ALL rights just to check if the service exists.
=> Ensure we close correct handle after checking if service exists

samples/complete.xml
Since I don't know what Rust would mean here, I assume that what's meant was Just. :)
=> Fix typo in the configuration sample

samples/complete.xml
The field `<serviceaccount>` seems like having a different structure, which not contains `domain` and `user`, but only a `username`.
=> Update serviceaccount field in sample complete.xml

doc/yamlConfigurationSchema.json
https://github.com/winsw/winsw/blob/9bfc034807a23e8de522efbad0a416b683557d4c/src/WinSW.Core/Configuration/YamlServiceConfig.cs#L376
Needs to be camlcase.
=> fix: wrong yaml schema for `logPath`
